# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/

    steps:
      - checkout
#      - run:
#          name: check working path
#          command: pwd
#      - run:
#          name: check working dir
#          command: ls -la
#      - run:
#          name: check working user
#          command: whoami

      # Download and cache dependencies
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "./package.json" }}
          # fallback to using the latest cache if no exact match is found
           - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}
        
      # run tests!
#      - run: pwd; ls -la; npm test
      - run: npm test

  deploy-job:
     docker:
       - image: circleci/node:10.15
     working_directory: ~/
     steps:
       - checkout
       - run:
           name: install firebase-tools
           command: npm install --save-dev firebase-tools
       - run:
           name: Deploy Master to Firebase
           command: cd test-project; ./node_modules/.bin/firebase deploy --project "$Firebase_Project" --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  -deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master